"""empty message

Revision ID: 8ce3acab31e4
Revises: fa507f590d60
Create Date: 2025-01-16 11:13:54.759044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce3acab31e4'
down_revision: Union[str, None] = 'fa507f590d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_vector_store_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_chat_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'files', 'vector_stores', ['vector_store_id'], ['vector_store_id'], ondelete='CASCADE')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_chat_id_fkey', 'files', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key('files_vector_store_id_fkey', 'files', 'vector_stores', ['vector_store_id'], ['vector_store_id'])
    # ### end Alembic commands ###
