"""empty message

Revision ID: b13ca025a0fc
Revises: 4df4f92ed76f
Create Date: 2025-01-15 17:24:25.549699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13ca025a0fc'
down_revision: Union[str, None] = '4df4f92ed76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.String(length=500), nullable=False))
    op.add_column('files', sa.Column('vector_store_id', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'vector_store_id')
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###
